# Generated by Django 6.0 on 2026-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_courses',
            field=models.ManyToManyField(blank=True, related_name='saved_by_students', to='users.courses'),
        ),
    ]
